<html>

<!--CSS-->
<link rel="stylesheet" href="assets/css/main.css" />
<!-- This publication listing, and corresponding CSS were extracted from an HTML export of her google doc of publications.  -->

<head>
    <title>Publications</title>
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

</head>

<body>
    <!-- Wrapper -->
    <div id="wrapper">
        <?php
      require("header.html");
      ?>
            <!-- Main -->
            <div id="main">
                <article class="post">
                    <h2>Publications</h2>
                    <p class="c31"><span class="c2 c5">Published Peer Reviewed Articles (h-index = 16)</span></p>
                    <ol class="c11 lst-kix_954g3qn5t9tc-0 start" start="1">
                      <li class="c7"><span class="c6">Cuttler, C.</span><span class="c3">, LaFrance, E. M., &amp; Craft, R. M. (in press). A large-scale naturalistic examination of the acute effects of cannabis on pain. </span><span class="c0 c2">Cannabis and Cannabinoid Research.</span><span class="c3"> doi:10.1089/can.2020.0068. </span></li>
                      <li class="c7"><span class="c3">Carter, G. T., McLaughlin, R. J., </span><span class="c6">Cuttler, C., </span><span class="c3">Sauber, G. J., Weeks, D., Hillard, C. J., &amp; Weiss, M. D. (2021). Endocannabinoids and related lipids serum from patients with amyotrophic lateral sclerosis. </span><span class="c0">Muscle & Nerve, 63(1), </span><span class="c3">120-126. doi: 10.1002/mus.27096.</span></li>
                      <li class="c7"><span class="c3">Mauzay, D., LaFrance, E. M., &amp; </span><span class="c6">Cuttler, C. </span><span class="c3"> (2021). Acute effects of cannabis on obsessive-compulsive disorder. </span><span class="c0">Journal of Affective Disorders, 279, </span><span class="c3">158-163. doi: 10.1016/j.jad.2020.09.124.</span></li>
                      <li class="c7"><span class="c3">Sheppard, L. D., </span><span class="c6">Cuttler, C., </span><span class="c3">Shin, E., & McLaughlin, R. J. (2021). Differences in cortisol following cooperative and competitive work-related tasks with same-sex versus opposite-sex partners. </span><span class="c0">Psychoneuroendocrinology, 124, </span><span class="c3">105063. doi: 10.1016/j.psyneuen.2020.105063. </span></li>
                      <li class="c7"><span class="c3">Warnick, B., Kier, A.S, LaFrance, E.M., &amp; </span><span class="c6">Cuttler, C. </span><span class="c3">(2021). Head in the clouds: The benefits and detriments of cannabis users’ creativity in new venture ideation: Countervailing effects of entrepreneurial passion and experience. </span><span class="c0">Journal of Business Venturing, 36 </span><span class="c3">106088. doi: 10.1016/j.busvent.2020.106088.</span></li>
                      <li class="c7"><span class="c3">Glodosky N. C., </span><span class="c6">Cuttler, C., </span><span class="c3">Freels, T. G., Wright, H. R., Rojas, M. J., Baglot, S. L., Hill, M. N., &amp; McLaughlin, R. J. (2020). Cannabis vapor self-administration elicits sex- and dose-specific alterations in stress reactivity in rats. </span><span class="c0">Neurobiology of Stress, 13, </span><span class="c3">100260. doi: 10.1016/j.ynstr.2020.100260</span></li>
                      <li class="c7"><span class="c6">Cuttler, C.,</span><span class="c3"> Spradlin, A., Cleveland, M., &amp; Craft, R. M. (2020). Short- and long-term effects of cannabis on headache and migraine. </span><span class="c0 c2">The Journal of Pain, 21(5-6), </span><span class="c3">722-730. doi: 10.1016/j.jpain.2019.11.001.</span></li>
                      <li class="c7"><span class="c3">Spradlin, A., Marcus, D. K., &amp; </span><span class="c6">Cuttler, C. </span><span class="c3"> (2020). The latent structure of cannabis misuse: A taxometric analysis. </span><span class="c0">Psychological Assessment, 32</span><span class="c3">(8), 803-808. doi: 10.1037/pas0000828.</span></li>
                      <li class="c7"><span class="c3">Freels, T. G., Baxter-Potter, L. N., Lugo, J. M., Glodosky, N. C., Wright, H. R., Baglot, S., Petrie, G., Yu, Z., Clowers, B. H., </span><span class="c6">Cuttler, C., </span><span class="c3"> Fuchs, R. A., Hill, M. N., &amp; McLaughlin, R. J. (2020). Vaporized cannabis extracts have reinforcing properties and support conditioned drug-seeking behaviour in rats. </span><span class="c0">Journal of Neuroscience, 40, </span><span class="c3">1897-1908. doi: 10.1523/jneurosci.2416-19.2020</span></li>
                      <li class="c7"><span class="c3">Glodosky N. C., &amp;</span><span class="c6">Cuttler, C. </span><span class="c3">(2020). Motives matter: Cannabis use motives moderate the associations between stress and negative affect. </span><span class="c0">Addictive Behaviors, 102, </span><span class="c3">106188. doi: 10.1016/j.addbeh.2019.106188.</span></li>
                      <li class="c7"><span class="c3">*LaFrance, E.M., *Glodosky, N., Bonn-Miller, M.  &amp; </span><span class="c6">Cuttler, C. </span><span class="c3">(2020). Short and long-term effects of cannabis on symptoms of post-traumatic stress disorder. </span><span class="c0">Journal of Affective Disorder, 274, </span><span class="c3">298-304. doi: 10.1016/j.jad.2020.05.132</span></li>
                      <li class="c7"><span class="c3">*Nusbaum, A. T., &amp; </span><span class="c6">Cuttler, C. </span><span class="c3">(2020). Hidden impacts of OER: Effects of OER on instructor ratings and course selection. </span><span class="c0">Frontiers in Education, 5, </span><span class="c3">72. doi: 10.3389/feduc.2020.00072.</span></li>
                      <li class="c7"><span class="c3">*Petrucci, A., *LaFrance, E. M., &amp; </span><span class="c6">Cuttler, C. </span><span class="c3">(2020). A comprehensive examination of the links between cannabis use and motivation. </span><span class="c0 c2">Substance Use & Misuse, 55, </span><span class="c3">1155-1164. doi: 10.10826084.2020.1729203</span></li>
                      <li class="c7"><span class="c3"> Anderson, T., &amp; </span><span class="c6">Cuttler, C. </span><span class="c3">(2020). Open to open? An exploration of textbook preferences and strategies to offset textbook costs in online vs. on-campus students. </span><span class="c0 c2">The International Review of Research in Open and Distributed Learning, 21,</span><span class="c3"> 40-60. doi: 10.19173/irrodl.v20i5.4141</span></li>
                      <li class="c7"><span class="c3">*LaFrance, E. M., *Stueber, A., *Glodosky, N. C., *Mauzay, D., &amp; </span><span class="c6">Cuttler, C. </span><span class="c3">(2020). Overbaked: Assessing and predicting adverse reactions to cannabis. </span><span class="c0 c2">Journal of Cannabis Research, 2, </span><span class="c3">1-10. doi: 10.1186/s42238-019-0013-x.</span></li>
                      <li class="c7"><span class="c3">*Nusbaum, A. T., </span><span class="c6">Cuttler, C. </span><span class="c3">&amp; Swindell, S. (2020). Open educational resources as a tool for educational equity: Evidence from an introductory psychology class. </span><span class="c0 c2">Frontiers in Education, 4</span><span class="c3"> 1-8. doi: 10.3389/feduc.2019.00152</span></li>
                      <li class="c7"><span class="c6">Cuttler, C.</span><span class="c3">, &amp; *Ryckman, M. (2019). Don’t call me delusional: Stigmatizing effects of noun labels on people with mental disorders. </span><span class="c0 c2">Stigma and Health, 4,</span><span class="c3"> 118-125. doi: 10.1037/sah0000132 </span></li>
                      <li class="c7"><span class="c6">Cuttler, C.</span><span class="c3">, Spradlin, A., Nusbaum, A.T., Whitney, P., Hinson, J.M., McLaughlin, R. (2019). Joint effects of stress and chronic cannabis use on prospective memory. </span><span class="c0 c2">Psychopharmacology, 236</span><span class="c3">, 1973-1983. doi: 10.1007/s00213-019-5184-9</span></li>
                      <li class="c7"><span class="c6">Cuttler, C.</span><span class="c3"> (2019). Students’ use and perceptions of the relevance and quality of open textbooks compared to traditional textbooks in online and traditional classroom environments. </span><span class="c0 c2">Psychology Learning &amp; Teaching</span><span class="c3">, 18, 65-83. doi: 10.1177/1475725718811300</span></li>
                      <li class="c7"><span class="c3">Sexton, M., </span><span class="c6">Cuttler, C.</span><span class="c3">, &amp; Mischley, L. (2019). A survey of acute effects of cannabis and withdrawal symptoms. Differential responses across user types and age. </span><span class="c0 c2">Journal of Alternative and Complementary Medicine</span><span class="c3">, 25, 326-335. doi: 10.1089/acm.2018.0319</span></li>
                      <li class="c7"><span class="c3">*Spradlin, A., &amp; </span><span class="c6">Cuttler, C.</span><span class="c3"> (2019). Problems associated with using cannabis to cope. </span><span class="c0 c2">Cannabis</span><span class="c3">, 2, 29-38. doi: 10.26828/cannabis.2019.01.001</span></li>
                      <li class="c7"><span class="c3">*Spradlin, A., </span><span class="c6">Cuttler, C.</span><span class="c3">, Bunce, J. P., &amp; Carrier, L. M. (2019). #Connected: Facebook may facilitate face-to-face relationships for introverts. </span><span class="c0 c2">Psychology of Popular Media Culture</span><span class="c3">, 8, 34-40.  doi: 10.1037/ppm0000162</span></li>
                      <li class="c7"><span class="c6">Cuttler, C.</span><span class="c3">, Connolly, C. P., *LaFrance, E. M., &amp; *Lowry, T. M. (2018). Resist forgetting: Effects of aerobic and resistance exercise on prospective and retrospective memory. </span><span class="c0 c2">Sport, Exercise, and Performance Psychology</span><span class="c3">, 7, 205-217. doi: 10.1037/spy0000112</span></li>
                      <li class="c7"><span class="c6">‡Cuttler, C.</span><span class="c3">, ‡Sexton, M., &amp; Mischley, L. (2018). Driving under the influence of cannabis: An examination of driving beliefs and practices of medical and recreational cannabis users in the United States. </span><span class="c0 c2">Cannabis</span><span class="c3">, 1, 1-13. doi: 10.26828/cannabis.2018.02.001</span></li>
                      <li class="c7"><span class="c6">Cuttler, C., </span><span class="c3">Spradlin, A., &amp; McLaughlin, R. J. (2018). A naturalistic examination of the perceived effects of cannabis on negative affect. </span><span class="c0">Journal of Affective Disorders, 235, </span><span class="c3">198-205</span><span class="c0">. </span><span class="c3">doi: 10.1016/j.jad.2018.04.054</span></li>
                      <li class="c7"><span class="c3">*Mauzay, D., &amp; </span><span class="c6">Cuttler, C. </span><span class="c3">(2018). Dysfunctional cognitions mediate the relationships between religiosity, paranormal beliefs, and symptoms of obsessive-compulsive.</span><span class="c0 c2">  Mental Health, Religion, &amp; Culture, 21, </span><span class="c3">838-850</span><span class="c0">. </span><span class="c3"> doi: 10.1080/13674676.2019.1583176</span></li>
                      <li class="c7"><span class="c3">Wilson, M., *Gogulski, H. Y., </span><span class="c6">Cuttler, C., </span><span class="c3">Bigand, T. L., Oluwoye, O., &amp; Barbosa-Leiker, C. (2018). Cannabis use moderates the relationship between pain and negative affect in adults with opioid use disorder. </span><span class="c0">Addictive Behaviors, 77, </span><span class="c3">225-231</span><span class="c0">. </span><span class="c3">doi: 10.1016/j.addbeh.2017.10.012</span></li>
                      <li class="c7"><span class="c6">Cuttler, C., </span><span class="c3">&amp; *Spradlin, A. (2017). Measuring cannabis consumption: Psychometric properties of the Daily Sessions, Frequency, Age of Onset, and Quantity of Cannabis Use Inventory (DFAQ-CU). </span><span class="c0">PLOS ONE. 12</span><span class="c1">(5): e0178194 doi: 10.1371/journal.pone.0178194</span></li>
                      <li class="c7"><span class="c6">Cuttler, C., *</span><span class="c3">Spradlin, A., *Nusbaum, A. T., Whitney, P., Hinson, J. M. &amp; McLaughlin, R. J. (2017). Blunted stress reactivity in chronic cannabis users. </span><span class="c0">Psychopharmacology, 234, </span><span class="c3">2299-2309</span><span class="c0">. </span><span class="c1">doi: 10.1007/s00213-017-4648-z</span></li>
                      <li class="c7"><span class="c3">*LaFrance, E., &amp; </span><span class="c6">Cuttler, C. </span><span class="c3">(2017).</span><span class="c6">&nbsp;</span><span class="c3">Inspired by Mary Jane? Mechanisms underlying enhanced creativity in cannabis users. </span><span class="c0">Consciousness and Cognition, 56, </span><span class="c3">68-76</span><span class="c0">. </span><span class="c3">doi: 10.1016/j.concog.2017.10.009</span></li>
                      <li class="c7"><span class="c3">*Nusbaum, A.T., Whitney, P., </span><span class="c6">Cuttler, C., *</span><span class="c3">Spradlin, A., Hinson, J. M., McLaughlin, R. J. (2017). Altered attentional control strategies in chronic cannabis users. </span><span class="c0">Drug and Alcohol Dependence, 181, </span><span class="c3">116-123</span><span class="c0">. </span><span class="c1">doi: 10.1016/j.drugalcdep.2017.09.019</span></li>
                      <li class="c7"><span class="c3">*Spradlin, A., *Mauzay, D., &amp; </span><span class="c6">Cuttler, C.</span><span class="c3">&nbsp;(2017). Symptoms of obsessive-compulsive disorder predict cannabis misuse. </span><span class="c0">Addictive Behaviors, 72, </span><span class="c3">159-164.</span><span class="c0">&nbsp;</span><span class="c1">doi: 10.1016/j.addbeh.2017.03.023</span></li>
                      <li class="c7"><span class="c6">Cuttler, C.,</span><span class="c3">&nbsp;Mischley, L., Sexton, M. (2016). Sex differences in cannabis use and effects: A cross-sectional survey of cannabis users. </span><span class="c0">Cannabis and Cannabinoid Research, 1</span><span class="c3">, 166-175.</span><span class="c0">&nbsp;</span><span class="c3">doi: 10.1089/can.2016.0010</span></li>
                      <li class="c7"><span class="c6">Cuttler, C., *</span><span class="c3">O&rsquo;Connell D., &amp; Marcus, D. K. (2016). Relationships between dimensions of impulsivity and prospective memory. </span><span class="c0">European Journal of Personality, 30, </span><span class="c3">83-91</span><span class="c0">. </span><span class="c3">doi: 10.1002/per.2038</span></li>
                      <li class="c7"><span class="c3">*Mauzay, D., *Spradlin, A., &amp; </span><span class="c6">Cuttler, C. </span><span class="c3">(2016). Devils, witches, and psychics: The role of thought-action fusion in the relationships between obsessive-compulsive features, religiosity, and paranormal beliefs. </span><span class="c0">Journal of Obsessive-Compulsive and Related Disorders, 11, </span><span class="c3">113-120</span><span class="c0">. </span><span class="c1">doi: 10.1016/j.jocrd.2016.10.003</span></li>
                      <li class="c7"><span class="c3">Sexton, M., </span><span class="c6">Cuttler, C., </span><span class="c3">Finnell, J., &amp; Mischley, L. (2016). A cross-sectional survey of medical cannabis users: Patterns of use and perceived efficacy. </span><span class="c0">Cannabis and Cannabinoid Research, 1, </span><span class="c3">131-138</span><span class="c0">. </span><span class="c3">doi: 10.1089/can.2016.0007</span></li>
                      <li class="c7"><span class="c6">Cuttler, C.,</span><span class="c3">&nbsp;*Relkov, T., &amp; Taylor, S. (2014) Quick to act, quick to forget: The link between impulsiveness and prospective memory. </span><span class="c0">European Journal of Personality, 28, </span><span class="c3">560-568</span><span class="c0">. </span><span class="c3">doi: </span><span class="c3 c8 c32">10.1002/per.1926</span></li>
                      <li class="c7"><span class="c6">Cuttler, C.,</span><span class="c3">&nbsp;*Alcolado, G. M., &amp; Taylor, S. (2013). Mediation and interaction effects of doubt, dysfunctional beliefs and memory confidence on the compulsion to check. </span><span class="c0">Journal of Obsessive-Compulsive and Related Disorders, 2</span><span class="c3">, 157-166</span><span class="c0">. </span><span class="c3">doi: 10.1016/j.jocrd.2013.02.002</span></li>
                      <li class="c7"><span class="c6">Cuttler, C.,</span><span class="c3">&nbsp;*Sirois-Delisle, V., *Alcolado, G. M., Radomsky, A. S., &amp; Taylor, S. (2013). Diminished confidence in prospective memory causes doubts and urges to check. </span><span class="c0">Journal of Behavior Therapy and Experimental Psychiatry, 44</span><span class="c3">, 329-334</span><span class="c0">.</span><span class="c26">&nbsp;</span><span class="c1">doi: 10.1016/j.jbtep.2013.01.001 &nbsp;</span></li>
                      <li class="c7"><span class="c6">Cuttler, C., </span><span class="c3">McLaughlin, R. J., &amp; Graf, P. (2012). Mechanisms underlying the link between cannabis use and prospective memory. </span><span class="c0">PLOS ONE, 7</span><span class="c3">(5): e36820. doi: 10.1371/journal.pone.0036820</span></li>
                      <li class="c7"><span class="c6">Cuttler, C., </span><span class="c3">&amp; Taylor, S. (2012). Did I forget to lock the door? The link between prospective memory failures and doubt in the compulsion to check. </span><span class="c0">Journal of Experimental Psychopathology, 3, </span><span class="c3">437-454</span><span class="c0">. </span><span class="c3">doi:10.5127/jep.021811 </span></li>
                      <li class="c7"><span class="c6">Cuttler, C., </span><span class="c3">Graf, P., Pawluski, J. L., &amp; Galea, L. A. M. (2011). Everyday life memory deficits in pregnant women. </span><span class="c0">Canadian Journal of Experimental Psychology, 65</span><span class="c3">, 27-37. doi: 10.1037/a002284 &nbsp; </span></li>
                      <li class="c7"><span class="c6">Cuttler, C., </span><span class="c3">&amp; Graf, P. (2009). Checking-in on the memory-deficit and meta-memory deficit theories of checking compulsions. </span><span class="c0">Clinical Psychology Review, 29</span><span class="c3">, 393-409</span><span class="c0">. </span><span class="c3">doi: 10.1016/j.cpr.2009.04</span></li>
                      <li class="c7"><span class="c6">Cuttler, C., </span><span class="c3">&amp; Graf, P. (2009). Sub-clinical compulsive checkers show impaired performance on habitual, event- and time-cued episodic prospective memory tasks. </span><span class="c0">Journal of Anxiety Disorders, 23</span><span class="c3">, 813-823</span><span class="c0">. </span><span class="c3">doi: 10.1016/j.janxdis.2009.03.006 &nbsp;</span></li>
                      <li class="c7"><span class="c6">Cuttler, C., </span><span class="c3">&amp; Graf, P. (2008). Sub-clinical checking compulsions are related to impaired prospective memory independently of depression, anxiety and distractibility. </span><span class="c0">Journal of Anxiety Disorders, 22</span><span class="c3">, 642-654</span><span class="c0">.</span><span class="c6">&nbsp;</span><span class="c3">doi: 10.1016/j.janxdis.2007.06.003 &nbsp;</span></li>
                      <li class="c7"><span class="c6">Cuttler, C., </span><span class="c3">&amp; Graf, P. (2007). Sub-clinical compulsive checkers&rsquo; prospective memory is impaired. </span><span class="c0">Journal of Anxiety Disorders, 21</span><span class="c3">, 338-352</span><span class="c0">. </span><span class="c3">doi: 10.1016/j.janxdis.2006.06.001</span></li>
                      <li class="c7"><span class="c6">Cuttler, C.,</span><span class="c3">&nbsp;&amp; Graf, P. (2007). Personality predicts prospective memory: An adult lifespan study. </span><span class="c0">Scandinavian Journal of Psychology, </span><span class="c1">48, 215-231. doi: 10.1111/j.1467-9450.2007.00570.x </span></li>
                      <li class="c7"><span class="c3">Cooper, B. S., </span><span class="c6">Cuttler, C.,</span><span class="c3">&nbsp;Dell, P., &amp; Yuille, J.C. (2006). Dissociation and amnesia: A study with male offenders. </span><span class="c0">International Journal of Forensic Psychology, 1</span><span class="c3">, 69-83</span><span class="c0">.</span></li>
                      <li class="c7"><span class="c3">Woodward, T. S., Moritz, S., Arnold, M. M., </span><span class="c6">Cuttler, C., </span><span class="c3">Whitman, J. C., &amp; Lindsay, S. (2006). Increased &ldquo;hindsight bias&rdquo; in schizophrenia. </span><span class="c0">Neuropsychology, 20</span><span class="c1">, 461-467. doi: 10.1037/0894-4105.20.4.461 </span></li>
                      <li class="c7"><span class="c3">Woodward, T. S., Moritz, S., </span><span class="c6">Cuttler, C.,</span><span class="c3">&nbsp;&amp; Whitman, J. C. (2006). The contribution of a cognitive bias against disconfirmatory evidence to delusions in schizophrenia. </span><span class="c0">Journal of Clinical and Experimental Neuropsychology, 28, </span><span class="c1">605-617. doi: 10.1080/13803390590949511</span></li>
                      <li class="c7"><span class="c3">Moritz, S., Kloss, M., Jacobsen, D., Fricke, S., </span><span class="c6">Cuttler, C.,</span><span class="c3">&nbsp;Brassen, S., &amp; Hand, I. (2005). Neurocognitive impairment does not predict treatment outcome in obsessive-compulsive disorder. </span><span class="c0">Behaviour Research and Therapy, 43</span><span class="c1">, 811- 819. doi: 10.1016/j.brat.2004.06.012</span></li>
                      <li class="c7"><span class="c3">Moritz, S., Woodward, T. S., Whitman, J., &amp; </span><span class="c6">Cuttler, C.</span><span class="c3">&nbsp;(2005). Confidence errors as a possible basis for delusions in schizophrenia. </span><span class="c0">Journal of Nervous and Mental Disease, 193</span><span class="c1">, 9-16. doi: 10.1097/01.nmd.0000149213.10692.00</span></li>
                      <li class="c7"><span class="c3">Moritz, S., Woodward, T. S., </span><span class="c6">Cuttler, C.,</span><span class="c3">&nbsp;Whitman, J., &amp; Watson, J. M. (2004). False memories in schizophrenia</span><span class="c0">. Neuropsychology, 18</span><span class="c1">, 276-283. doi: 10.1037/0894-4105.18.2.276 </span></li>
                      <li class="c15"><span class="c3">Woodward, T. S., Whitman, J. C., </span><span class="c6">Cuttler, C.,</span><span class="c3">&nbsp;Moritz, S. (2003). Source memory bias associated with reality distortion in schizophrenia. </span><span class="c0">Schizophrenia Research, 60, </span><span class="c3">186-187. </span><span class="c0">&nbsp;</span><span class="c1">doi: 10.1016/S0920-9964(03)81090-3</span></li>
                    </ol>
                    <p class="c31"><span class="c27">Working Group Peer Reviewed Articles </span></p>
                    <ol class="c11 lst-kix_954g3qn5t9tc-0" start="35">
                      <li class="c15"><span class="c3">Bravo, A. J., Weinstein, A. P., Pearson, M. R., &amp; </span><span class="c6">Protective Strategies Study Team </span><span class="c3">(2019). The relationship between risk factors and alcohol and marijuana use outcomes among concurrent users: A comprehensive examination of protective behavioral strategies. </span><span class="c0">Journal of Studies on Alcohol and Drugs, 80,</span><span class="c1"> 102-108. doi: 10.15288/jsad.2019.80.102</span></li>
                      <li class="c15"><span class="c3">Gonzalez, V. M., Bravo, A. J., Crouch, M. C., &amp; </span><span class="c6">Protective Strategies Study Team </span><span class="c3">(2019). Endorsement of the “firewater myth” affects the use of protective behavioral strategies among American Indian and Alaska Native students. </span><span class="c0">Addictive Behaviors, 93, </span><span class="c1">78-85. doi: 10.1016/j.addbeh.2019.01.027</span></li>
                      <li class="c15"><span class="c3">Jordan, H. R., Madson, M. B., Nicholson, B. C., Bravo, A. J., Pearson, M. R., &amp; </span><span class="c6">Protective Strategies Study Team </span><span class="c3">(2019). Posttraumatic stress disorder symptoms and problematic alcohol use in college students: The moderating role of alcohol protective behavioral strategies and gender. </span><span class="c0">Psychological Trauma: Theory, Research, Practice, & Policy, 11,</span><span class="c1"> 247-255. doi: 10.1037.tra0000417</span></li>
                      <li class="c15"><span class="c3">Looby, A., Bravo, A. J., Kilwein, T. M, Zimmerman, L., Pearson, M. R, &amp; </span><span class="c6">Protective Strategies Study Team </span><span class="c3">(2019). Alcohol-related protective hehavioral strategies as a mediator of the relationship between drinking motives and risky sexual behaviors. </span><span class="c0">Addictive Behaviors, 93,</span><span class="c1"> 1-8. doi: 10.1016/j.addbeh.2019.01.009</span></li>
                      <li class="c15"><span class="c3">Pearson, M. R., Bravo, A. J.,  &amp; </span><span class="c6">Protective Strategies Study Team </span><span class="c3">(2019). Marijuana protective behavioral strategies and marijuana refusal self-efficacy: Independent and interactive effects on marijuana-related outcomes. </span><span class="c0">Psychology of Addictive Behaviors, 33,</span><span class="c1"> 412-419. doi: 10/1037/adb0000445</span></li>
                      <li class="c15"><span class="c3">Villarosa-Hurlocker, M. C., Bravo, A. J., Pearson, M. R., &amp; </span><span class="c6">Protective Strategies Study Team </span><span class="c3">(2019). The relationship between social anxiety and alcohol and marijuana use outcomes among concurrent users: A motivational model of substance use. </span><span class="c0">Alcoholism: Clinical and Experimental Research. </span><span class="c1">Advance online publication. doi: 10.1111/acer.13966</span></li>
                      <li class="c15"><span class="c3">Wong, M. M., Craun, E., A., Bravo, A. J., Pearson, M. R., &amp; </span><span class="c6">Protective Strategies Study Team </span><span class="c3">(2019). Insomnia symptoms, cannabis protective behavioral strategies, and hazardous cannabis use among U.S. college students.  </span><span class="c0">Experimental Clinical Psychopharmacology. Advance online publication.</span><span class="c1"> doi: 10.1037/</span></li>
                      <li class="c15"><span class="c3">Bravo, A. J., Villarosa-Hurlocker, M. C., Pearson, M. R., &amp; </span><span class="c6">Protective Strategies Study Team </span><span class="c3">(2018). College student mental health: An evaluation of the DSM 5 Self-Rated Level 1 Cross Cutting Symptom Measure. </span><span class="c0">Psychological Assessment. </span><span class="c1">doi: 10.1037/pas0000628</span></li>
                      </ol>
                    <p class="c31"><span class="c27">Invited Commentary</span></p>
                    <ol class="c11 lst-kix_954g3qn5t9tc-0" start="36">
                      <li class="c15"><span class="c3">Spradlin, A., *Mauzay, D., &amp;</span><span class="c6">&nbsp;Cuttler, C. </span><span class="c3">(2017). A response to the commentary by Storch and Kay: Gaps in knowledge on the treatment of cannabis users with OCD. </span><span class="c0">Addictive Behaviors. </span><span class="c1">doi: 10.1016/j.addbeh.2017.07.029</span></li>
                    </ol>
                    <p class="c31"><span class="c27">Invited Book Review</span></p>
                    <ol class="c11 lst-kix_954g3qn5t9tc-0" start="36">
                      <li class="c15"><span class="c6">&nbsp;Cuttler, C. </span><span class="c3"> (in press). Cannabinoids and the Brain: A balanced perspective on our current state of knowledge. </span><span class="c0">Applied Neuropsychology: Adult. </span><span class="c1">Advance online publication. doi: 10.1080/23279095.2018.1557364.</span></li>
                    </ol>
                    <p class="c4"><span class="c5 c2">Book Chapter</span></p>
                    <ol class="c11 lst-kix_l7d7awojym6j-0 start" start="1">
                      <li class="c35"><span class="c3">Taylor, S., Abramowitz, J. S., McKay, D., &amp; </span><span class="c6">Cuttler, C.</span><span class="c3">&nbsp;(2011). Cognitive approaches to understanding obsessive-compulsive and related disorders. In G. Steketee (Ed.), </span><span class="c0">Oxford handbook of obsessive compulsive and spectrum disorders </span><span class="c1">(pp. 233-252). New York: Oxford University Press.</span></li>
                    </ol>
                    <p class="c4"><span class="c27">Books</span></p>
                    <div style="line-height:75%;">
                        <br> <!--this is a hack-->
                    </div>
                    <ol class="c11 lst-kix_5luesrtyjzil-0 start" start="1">
                      <li class="c7"><span class="c6">Cuttler, C.</span><span class="c1">&nbsp;(in press). A student guide to SPSS. Third edition. Dubuque, IA: Kendall Hunt Publishing.</span></li>
                      <li class="c7"><span class="c3">Jhangiani, R. S., Chiang, I. A. &amp; </span><span class="c6">Cuttler, C.</span><span class="c3">, & Leighton, D. C., </span><span class="c1">&nbsp;(2019). Research methods in psychology: 4th edition. Pullman, WA: Open Text Kwantlen Polytechnic University. Retrieve at: </span><span class="c3 c13"><a class="c23" href="https://kpu.pressbooks.pub/psychmethods4e/">https://kpu.pressbooks.pub/psychmethods4e/</a></span></li>
                      <li class="c7"><span class="c3">Price, P. C., Jhangiani, R. S., Chiang, I. A., Leighton, D. C., &amp; </span><span class="c6">Cuttler, C. </span><span class="c3">(2017). Research methods in psychology: 3</span><span class="c20 c25">rd</span><span class="c3">&nbsp;American edition. Pullman, WA: Open Text WSU. Retrieve at: </span><span class="c3 c13"><a class="c23" href="https:opentext.wsu.edu/carriecuttler/">https:opentext.wsu.edu/carriecuttler</a></span></li>
                      <li class="c7"><span class="c6">Cuttler, C.</span><span class="c1">&nbsp;(2014). A student guide to SPSS. Second edition. Dubuque, IA: Kendall Hunt Publishing. </span></li>
                      <li class="c7"><span class="c6">Cuttler, C.</span><span class="c1">&nbsp;(2010). A student guide to SPSS. Dubuque, IA: Kendall Hunt Publishing. </span></li>
                      <li class="c7"><span class="c6">Cuttler, C.</span><span class="c1">&nbsp;(2010). Research methods in psychology: Student lab guide. Dubuque, IA: Kendall Hunt Publishing. </span></li>
                      <li class="c15"><span class="c6">Cuttler, C.</span><span class="c1">&nbsp;(2010). Research methods in psychology: Instructor&rsquo;s manual. Dubuque, IA: Kendall Hunt Publishing. </span></li>
                    </ol>
                    <p class="c31"><span class="c27">Edited Books</span><span class="c6 c2 c8">&nbsp;</span></p>
                    <ol class="c11 lst-kix_5luesrtyjzil-0" start="6">
                        <li class="c7" id="h.gjdgxs-1"><span class="c3">Bridley, A. &amp; Daffin, L. W. Jr. (2018). Abnormal Psychology: 1</span><span class="c20 c25">st</span><span class="c3">&nbsp;edition. </span><span class="c6">C. Cuttler</span><span class="c3">&nbsp;(Ed.). Pullman, WA: Open Text WSU. Retrieve at:</span><span class="c13 c3"><a class="c23" href="https://opentext.wsu.edu/abnormalpsychology">&nbsp;https://opentext.wsu.edu/abnormalpsychology/</a></span></li>
                    </ol>

                    * mentored student </br>
                    &Dagger; co-first author
                </article>
            </div>
            <?php
require("sidebar.html");
?>
                <!-- Scripts -->
                <script src="/assets/js/jquery.min.js"></script>
                <script src="/assets/js/skel.min.js"></script>
                <script src="/assets/js/util.js"></script>
                <script src="/assets/js/main.js"></script>
</body>

</html>
